@HOST=http://localhost:8080

@ID=


### @name Read
GET {{HOST}}/doctors/{{ID}}

### @name List
GET {{HOST}}/doctors

### @name ListComplete
GET {{HOST}}/doctors/complete

### @name Create
POST {{HOST}}/doctors
Content-Type: application/json

{
    "name": "John Doe",
    "crm": "000000",
    "email": "email@email.com",
    "specialty": "CARDIOLOGY",
    "phone": "5511999999999",
    "address": {
        "firstLine": "Street X",
        "secondLine": "Lower",
        "number": 42,
        "zipCode": "00000000",
        "complement": "High tree"
    }
}

### @name Update
PUT {{HOST}}/doctors
Content-Type: application/json

{
    "id": "6648ca74-b39b-46a1-8248-83fc05d8d622",
    "email": "xxxx@xxx.com"
}

### @name Delete
DELETE {{HOST}}/doctors/{{ID}}
