@HOST=http://localhost:8080

@ID=


### @name Read
GET {{HOST}}/patients/{{ID}}

### @name List
GET {{HOST}}/patients

### @name ListComplete
GET {{HOST}}/patients/complete

### @name Create
POST {{HOST}}/patients
Content-Type: application/json

{
    "name": "John Doe",
    "cpf": "00000000000",
    "email": "email@email.com",
    "phone": "5511999999999",
    "address": {
        "firstLine": "Street X",
        "secondLine": "Lower",
        "number": 42,
        "zipCode": "00000000",
        "complement": "High tree"
    }
}

### @name Update
PUT {{HOST}}/patients
Content-Type: application/json

{
    "id": "{{ID}}",
    "email": "example@email.com"
}

### @name Delete
DELETE {{HOST}}/patients/{{ID}}
